<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__vc_single_image-img attachment-full wd_879ad7</name>
   <tag></tag>
   <elementGuidId>dcd214fc-10ae-4d1f-9d3f-b4d5c6811998</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='custom_html-2']/div/section[2]/div/div[2]/div/div/div/div/div/div/div/figure/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.vc_single_image-wrapper.vc_box_border_grey > img.vc_single_image-img.attachment-full.wd-lazy-load.wd-lazy-fade.wd-loaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Đối tác của ACET&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7308bba0-9ab9-46e8-af7c-427220aa65bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>800</value>
      <webElementGuid>0ad5860f-4487-4762-8c7d-67afda95fac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>167</value>
      <webElementGuid>22dcac1c-712f-44ce-a080-7956896be278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://acet.edu.vn/wp-content/uploads/2020/02/idp-banner.jpg</value>
      <webElementGuid>9904efd3-efba-4960-85d3-c661404a8f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vc_single_image-img attachment-full wd-lazy-load wd-lazy-fade wd-loaded</value>
      <webElementGuid>f5143711-77cd-4ac1-b570-9923f3a2f1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Đối tác của ACET</value>
      <webElementGuid>24f07b96-07bc-453c-8a67-607d6e8d5a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>be2fc681-dc2a-4734-959b-ed30d1d578aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>b0288913-b11a-4ec8-9f0f-457a0dc55be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>idp-banner</value>
      <webElementGuid>7ba95204-1a4c-4ec7-9753-8f0b0d33248b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://acet.edu.vn/wp-content/uploads/2020/02/idp-banner.jpg 800w, https://acet.edu.vn/wp-content/uploads/2020/02/idp-banner-300x63.jpg 300w, https://acet.edu.vn/wp-content/uploads/2020/02/idp-banner-768x160.jpg 768w</value>
      <webElementGuid>5a201521-380f-429e-a1a8-74bce8246f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 800px) 100vw, 800px</value>
      <webElementGuid>d4e8ab42-52ef-4b87-a2cf-abc90c379f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wood-src</name>
      <type>Main</type>
      <value>https://acet.edu.vn/wp-content/uploads/2020/02/idp-banner.jpg</value>
      <webElementGuid>f2ce2898-ddfa-4b06-a0c7-c193a37bfddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-srcset</name>
      <type>Main</type>
      <value>https://acet.edu.vn/wp-content/uploads/2020/02/idp-banner.jpg 800w, https://acet.edu.vn/wp-content/uploads/2020/02/idp-banner-300x63.jpg 300w, https://acet.edu.vn/wp-content/uploads/2020/02/idp-banner-768x160.jpg 768w</value>
      <webElementGuid>22d62f68-bc81-4047-9e5d-235060b78854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom_html-2&quot;)/div[@class=&quot;textwidget custom-html-widget&quot;]/section[@class=&quot;vc_section vc_custom_1576836871366 vc_section-has-fill&quot;]/div[@class=&quot;vc_row wpb_row vc_row-fluid&quot;]/div[@class=&quot;wpb_column vc_column_container vc_col-sm-12 vc_col-lg-10&quot;]/div[@class=&quot;vc_column-inner&quot;]/div[@class=&quot;wpb_wrapper&quot;]/div[@class=&quot;vc_row wpb_row vc_inner vc_row-fluid vc_custom_1602907733113 vc_row-o-content-middle vc_row-flex&quot;]/div[@class=&quot;wpb_column vc_column_container vc_col-sm-4 vc_col-lg-4 vc_col-md-4 vc_col-xs-4&quot;]/div[@class=&quot;vc_column-inner&quot;]/div[@class=&quot;wpb_wrapper&quot;]/div[@class=&quot;wpb_single_image wpb_content_element vc_align_center&quot;]/figure[@class=&quot;wpb_wrapper vc_figure&quot;]/a[@class=&quot;vc_single_image-wrapper   vc_box_border_grey&quot;]/img[@class=&quot;vc_single_image-img attachment-full wd-lazy-load wd-lazy-fade wd-loaded&quot;]</value>
      <webElementGuid>5c0b6c6e-1a57-4c88-b030-d75c6bd83ffa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom_html-2']/div/section[2]/div/div[2]/div/div/div/div/div/div/div/figure/a/img</value>
      <webElementGuid>d42c87fd-1e3d-4d25-a1f2-956b8474bcfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Đối tác của ACET']</value>
      <webElementGuid>248a0446-8789-4418-8405-da43f5358942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/a/img</value>
      <webElementGuid>b02551c0-1df0-42bf-8aae-c992c6a1904f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://acet.edu.vn/wp-content/uploads/2020/02/idp-banner.jpg' and @alt = 'Đối tác của ACET' and @title = 'idp-banner']</value>
      <webElementGuid>ac2303e2-74aa-468b-89ca-faaa70db7617</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
