<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__vc_single_image-img attachment-full wd_879ad7_1</name>
   <tag></tag>
   <elementGuidId>8dca185a-6eca-457a-8d55-122ed3358cfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='custom_html-2']/div/section[2]/div/div[2]/div/div/div/div[3]/div/div/div/figure/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Đối tác của ACET&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>70e1dafb-e39d-4c34-a70e-e5919f713f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>800</value>
      <webElementGuid>d6323b2c-806a-4a05-b3fe-8b12bc611c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>167</value>
      <webElementGuid>9d91bde6-9013-4841-aad5-9a06a50d7ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://acet.edu.vn/wp-content/uploads/2020/02/neas-banner.jpg</value>
      <webElementGuid>25261910-02df-4d41-9b0a-9e68d4eeff80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vc_single_image-img attachment-full wd-lazy-load wd-lazy-fade wd-loaded</value>
      <webElementGuid>38cc5071-84ce-4392-a52e-6d5f9f57a21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Đối tác của ACET</value>
      <webElementGuid>12a70be2-975d-44b6-bd7f-c6eb57587698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>a6a87193-0637-4fe8-8aff-36b4eb9456b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>3b4cef74-8c95-4fc1-ae61-f5d6829b8429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>neas-banner</value>
      <webElementGuid>5577de11-e31b-49f3-b42c-f53971db0be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://acet.edu.vn/wp-content/uploads/2020/02/neas-banner.jpg 800w, https://acet.edu.vn/wp-content/uploads/2020/02/neas-banner-300x63.jpg 300w, https://acet.edu.vn/wp-content/uploads/2020/02/neas-banner-768x160.jpg 768w</value>
      <webElementGuid>32ae907c-af09-47f7-a43f-f8ccac627af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 800px) 100vw, 800px</value>
      <webElementGuid>066bafe8-b2a2-45d6-b5ef-3dc03b22b6e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wood-src</name>
      <type>Main</type>
      <value>https://acet.edu.vn/wp-content/uploads/2020/02/neas-banner.jpg</value>
      <webElementGuid>1db2c71f-9ab0-4c27-bee2-8f8c2bffad91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-srcset</name>
      <type>Main</type>
      <value>https://acet.edu.vn/wp-content/uploads/2020/02/neas-banner.jpg 800w, https://acet.edu.vn/wp-content/uploads/2020/02/neas-banner-300x63.jpg 300w, https://acet.edu.vn/wp-content/uploads/2020/02/neas-banner-768x160.jpg 768w</value>
      <webElementGuid>ff25630f-4282-4db8-8052-e487873bf6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom_html-2&quot;)/div[@class=&quot;textwidget custom-html-widget&quot;]/section[@class=&quot;vc_section vc_custom_1576836871366 vc_section-has-fill&quot;]/div[@class=&quot;vc_row wpb_row vc_row-fluid&quot;]/div[@class=&quot;wpb_column vc_column_container vc_col-sm-12 vc_col-lg-10&quot;]/div[@class=&quot;vc_column-inner&quot;]/div[@class=&quot;wpb_wrapper&quot;]/div[@class=&quot;vc_row wpb_row vc_inner vc_row-fluid vc_custom_1602907733113 vc_row-o-content-middle vc_row-flex&quot;]/div[@class=&quot;wpb_column vc_column_container vc_col-sm-4 vc_col-lg-4 vc_col-md-4 vc_col-xs-4&quot;]/div[@class=&quot;vc_column-inner&quot;]/div[@class=&quot;wpb_wrapper&quot;]/div[@class=&quot;wpb_single_image wpb_content_element vc_align_center&quot;]/figure[@class=&quot;wpb_wrapper vc_figure&quot;]/a[@class=&quot;vc_single_image-wrapper   vc_box_border_grey&quot;]/img[@class=&quot;vc_single_image-img attachment-full wd-lazy-load wd-lazy-fade wd-loaded&quot;]</value>
      <webElementGuid>5d71d753-ed96-489c-94d0-6e7309d723e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='custom_html-2']/div/section[2]/div/div[2]/div/div/div/div[3]/div/div/div/figure/a/img</value>
      <webElementGuid>31e48577-ce87-40cc-9e30-e781683df95b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Đối tác của ACET'])[2]</value>
      <webElementGuid>497ae5ac-a67f-4d70-a708-63038bef8e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/figure/a/img</value>
      <webElementGuid>3c2e1536-0e8e-4ec8-9509-af1c061455ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://acet.edu.vn/wp-content/uploads/2020/02/neas-banner.jpg' and @alt = 'Đối tác của ACET' and @title = 'neas-banner']</value>
      <webElementGuid>a8ba3d36-5a56-467f-ae6a-2f74f86d2f70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
