<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Lin h</name>
   <tag></tag>
   <elementGuidId>b5e6becb-d7ba-4827-936c-7aed478df1c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-3238']/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-3238 > a.woodmart-nav-link > span.nav-link-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Main navigation&quot;i >> internal:role=link[name=&quot;Liên hệ&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7a86dcfe-cd71-413b-bdf4-038b769f3f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link-text</value>
      <webElementGuid>cdb6ddb9-8a37-41e3-8fb2-6c1c588abec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Liên hệ</value>
      <webElementGuid>1892e1e6-66c5-4b28-9767-901e96eee230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-3238&quot;)/a[@class=&quot;woodmart-nav-link&quot;]/span[@class=&quot;nav-link-text&quot;]</value>
      <webElementGuid>70f74d09-6886-4aa7-8e31-d313ca81dba9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-3238']/a/span</value>
      <webElementGuid>3eb12de1-ab59-463a-b12a-a249b978e79b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nhân viên'])[1]/following::span[1]</value>
      <webElementGuid>8f22755f-9ba9-4c55-8636-83bd2ffbf33c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giáo viên'])[1]/following::span[1]</value>
      <webElementGuid>4fa7c240-7a4a-4899-a3d7-e53ae762feb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::span[2]</value>
      <webElementGuid>c018bf89-8e0a-40a7-a3dc-2695d6ee1507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[2]/preceding::span[3]</value>
      <webElementGuid>5cca598a-a88e-4a74-b86f-dc9d09aa890c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Liên hệ']/parent::*</value>
      <webElementGuid>bf0f7941-d33a-4219-af0e-e225847570d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a/span</value>
      <webElementGuid>4edc53af-e08d-498d-a975-58e7ff28a09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Liên hệ' or . = 'Liên hệ')]</value>
      <webElementGuid>3368572b-2305-47ff-a1eb-ebe2c4cfdc86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
