<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Xem thm</name>
   <tag></tag>
   <elementGuidId>a5c64853-a1a6-4aac-89f9-3dc39211d5c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-3233']/div/section/div/div[2]/div/div/div/div/table/tbody/tr[2]/td[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Schools Link Teachers Hanoi 05 31/12/2023 Xem thêm&quot;i] >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5ff13ab4-c681-43d0-90bb-4a00781db17c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://acet.edu.vn/acet-is-recruiting-teachers-for-schools-link-partnership-programme/</value>
      <webElementGuid>93c7fd76-6321-4b0e-a168-5f959d03dff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>4d8f6012-ca81-4a6d-bc5a-55f8afd18b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Xem thêm</value>
      <webElementGuid>d407e30c-a376-4024-96f0-de966a0601ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-3233&quot;)/div[@class=&quot;entry-content&quot;]/section[@class=&quot;wpb-content-wrapper&quot;]/div[@class=&quot;vc_row wpb_row vc_row-fluid&quot;]/div[@class=&quot;wpb_column vc_column_container vc_col-sm-10&quot;]/div[@class=&quot;vc_column-inner&quot;]/div[@class=&quot;wpb_wrapper&quot;]/div[@class=&quot;wpb_raw_code wpb_content_element wpb_raw_html&quot;]/div[@class=&quot;wpb_wrapper&quot;]/table[@class=&quot;table table-tuyen-dung&quot;]/tbody[1]/tr[2]/td[@class=&quot;center&quot;]/a[@class=&quot;btn&quot;]</value>
      <webElementGuid>0cb17836-8442-4dde-8c53-c70fa15f37f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-3233']/div/section/div/div[2]/div/div/div/div/table/tbody/tr[2]/td[5]/a</value>
      <webElementGuid>e53fea70-5ec1-47d7-97a8-067473ff4dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Xem thêm')]</value>
      <webElementGuid>8ddb55f6-547c-4da7-90ae-7209cb973ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hanoi'])[1]/following::a[1]</value>
      <webElementGuid>a8020560-c293-487f-9b5f-e7fb03d02cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schools Link Teachers'])[1]/following::a[1]</value>
      <webElementGuid>5117417e-73c8-4ee7-a4d9-2fa6aafe4acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teachers'])[1]/preceding::a[1]</value>
      <webElementGuid>06c87be6-965d-4ea0-bb2d-61025b8c86ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hà Nội &amp; Hồ Chí Minh'])[1]/preceding::a[1]</value>
      <webElementGuid>97d8c6a4-7ea7-43fb-93eb-e57322210afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Xem thêm']/parent::*</value>
      <webElementGuid>9d5f7073-06d1-4c0e-84d5-60584d39702f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://acet.edu.vn/acet-is-recruiting-teachers-for-schools-link-partnership-programme/')]</value>
      <webElementGuid>77f9ba55-c5da-4c69-aa1a-397bb5c2680e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a</value>
      <webElementGuid>1d3d8613-6e46-45ad-8f2e-6da75916f9d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://acet.edu.vn/acet-is-recruiting-teachers-for-schools-link-partnership-programme/' and (text() = 'Xem thêm' or . = 'Xem thêm')]</value>
      <webElementGuid>4ba76d97-5e33-4505-b50b-79d3df3ab35b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
