<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kim tra trnh  Ting Anh</name>
   <tag></tag>
   <elementGuidId>5aa97ae0-3c6f-4136-be0f-3b4ae6b8f7d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-3228']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-3228 > a.woodmart-nav-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Main navigation&quot;i >> internal:role=link[name=&quot;Kiểm tra trình độ Tiếng Anh&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>14e00881-94ce-4cf9-a046-a64a0397ce48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://acet.edu.vn/kiem-tra-trinh-do-tieng-anh/</value>
      <webElementGuid>6b82969f-0118-4a6d-a8fc-7b138694b69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woodmart-nav-link</value>
      <webElementGuid>401f077b-d8d5-4429-b942-4ed1ea2b1388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kiểm tra trình độ Tiếng Anh</value>
      <webElementGuid>874e789a-1f85-4474-aff4-6ce063780684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-3228&quot;)/a[@class=&quot;woodmart-nav-link&quot;]</value>
      <webElementGuid>d61bb1d2-6399-438d-8891-673ad0f21aa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-3228']/a</value>
      <webElementGuid>7d2de8fb-ae77-40e0-8f2f-7289c86774fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kiểm tra trình độ Tiếng Anh')]</value>
      <webElementGuid>8006a375-40ca-433c-8b23-da2232ae5899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My IELTS Classroom'])[1]/following::a[1]</value>
      <webElementGuid>5d5853b1-a16a-430e-9d6c-0157c73daeec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Câu chuyện thành công'])[1]/following::a[2]</value>
      <webElementGuid>c4408fa5-865b-42eb-955b-41656619dc44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kinh nghiệm học IELTS'])[1]/preceding::a[1]</value>
      <webElementGuid>04cfcace-c563-42ee-9e26-bb4cd7d31e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDP IELTS &amp; Du Học'])[1]/preceding::a[2]</value>
      <webElementGuid>e805ac9b-916f-4077-aefe-062ba0078dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kiểm tra trình độ Tiếng Anh']/parent::*</value>
      <webElementGuid>71369014-d4c0-4655-8ca6-17e0b4132435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://acet.edu.vn/kiem-tra-trinh-do-tieng-anh/')]</value>
      <webElementGuid>69e26f23-9059-416f-a8d4-a36a86108646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/div/ul/li/a</value>
      <webElementGuid>70cca147-6852-40c0-9d6b-170f177ed4f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://acet.edu.vn/kiem-tra-trinh-do-tieng-anh/' and (text() = 'Kiểm tra trình độ Tiếng Anh' or . = 'Kiểm tra trình độ Tiếng Anh')]</value>
      <webElementGuid>d62a2b09-c9e0-4f78-89ed-ae0618e7bc2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
