<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_My IELTS Classroom</name>
   <tag></tag>
   <elementGuidId>073f1de7-03bb-4466-938a-46d16eac84b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-3227']/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-3227 > a.woodmart-nav-link > span.nav-link-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Main navigation&quot;i >> a >> internal:has-text=&quot;My IELTS Classroom&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e7227f49-33d5-4309-a71d-b86eb59bc757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link-text</value>
      <webElementGuid>86a40d23-90a3-4573-ae55-22e1e5a2c1c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My IELTS Classroom</value>
      <webElementGuid>532314ad-4318-4c50-bb8c-1e1bcb5b774e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-3227&quot;)/a[@class=&quot;woodmart-nav-link&quot;]/span[@class=&quot;nav-link-text&quot;]</value>
      <webElementGuid>9217d913-63e9-47e1-ba62-eb18895736e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-3227']/a/span</value>
      <webElementGuid>f4b201c7-d850-4492-b99a-1bf2c8e800c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Câu chuyện thành công'])[1]/following::span[1]</value>
      <webElementGuid>a52e4221-17c6-496e-81b9-4a37ee435f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACET Hồ Chí Minh'])[1]/following::span[1]</value>
      <webElementGuid>31583462-2f18-4654-ad4e-85c5bca9ec63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kiểm tra trình độ Tiếng Anh'])[1]/preceding::span[1]</value>
      <webElementGuid>fde52a7e-be92-4139-8d1e-78cb129335dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kinh nghiệm học IELTS'])[1]/preceding::span[1]</value>
      <webElementGuid>ebb6931f-b49c-4c3b-94d4-9452c5cd8a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My IELTS Classroom']/parent::*</value>
      <webElementGuid>cbf485ba-7140-483f-ac84-420cc9403426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/span</value>
      <webElementGuid>6efc390e-1053-40ad-b5d8-bab84b472d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'My IELTS Classroom' or . = 'My IELTS Classroom')]</value>
      <webElementGuid>a47fb18b-29ed-46ae-9e5a-4bf1ea35e027</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
