<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ti sao chn ACET</name>
   <tag></tag>
   <elementGuidId>e9da4ac7-b5dd-4601-82b9-83c8b5cf7cfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-3212']/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.nav-link-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Main navigation&quot;i >> a >> internal:has-text=&quot;Tại sao chọn ACET&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0a199037-451c-4e96-b98a-8e538eedfe72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link-text</value>
      <webElementGuid>3abec76f-dc77-4c60-8d11-816c4a088fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tại sao chọn ACET</value>
      <webElementGuid>72ec553c-67d2-4834-858b-0f453109193d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-3212&quot;)/a[@class=&quot;woodmart-nav-link&quot;]/span[@class=&quot;nav-link-text&quot;]</value>
      <webElementGuid>fe785d3d-4951-41aa-a1f1-acf4747fab7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-3212']/a/span</value>
      <webElementGuid>9e0be6e2-cb2e-4295-ad53-9684acc20935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Viet'])[1]/following::span[1]</value>
      <webElementGuid>59198e62-1aa6-40b1-ae14-cc521b8909a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eng'])[1]/following::span[2]</value>
      <webElementGuid>eee6baff-7f36-4e02-ae7c-f7f8f8ac9f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lý do chọn ACET'])[1]/preceding::span[1]</value>
      <webElementGuid>3c4498e5-a3ad-453e-8527-70ddf17db387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anh Ngữ Học Thuật'])[1]/preceding::span[1]</value>
      <webElementGuid>c52a09b9-73cb-42b3-93ac-7a04242f7ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tại sao chọn ACET']/parent::*</value>
      <webElementGuid>2d997f5c-df60-4eb1-9a0c-016ed3356a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/span</value>
      <webElementGuid>5ca5217a-8569-4c7b-ab7c-51368220e09d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tại sao chọn ACET' or . = 'Tại sao chọn ACET')]</value>
      <webElementGuid>6b649d2c-3cff-4c14-b7fc-14489ad581e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
