<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Resources</name>
   <tag></tag>
   <elementGuidId>8ccc5e7b-de33-40d5-8f01-a0a1e19ec74d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-53']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-53 > a.nav-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#menu-item-53 >> internal:role=link[name=&quot;Resources&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1bf61673-7c9e-45a3-8b55-c6b26ece8a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Resources</value>
      <webElementGuid>2ee9c85d-eb72-4bba-824d-3ab625c8bb2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://neas.org.au/resources/</value>
      <webElementGuid>b3dd92b0-8b97-4d87-9a06-fc627f72a530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>3c96c969-5a65-4d77-824d-f39d1b7c81ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Resources</value>
      <webElementGuid>972c8034-f898-48cb-949a-502f74aca8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-53&quot;)/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>35be76be-df1b-44a7-b959-6bb62d4ad3d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-53']/a</value>
      <webElementGuid>9eb434b3-fc87-4bfe-9d77-a72adcb691f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Resources')]</value>
      <webElementGuid>289984b4-ede9-4b26-bd82-5b5b327e0835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Professional Development'])[1]/following::a[1]</value>
      <webElementGuid>10931d39-50c4-4837-91df-8a77d33035c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quality Assurance'])[1]/following::a[2]</value>
      <webElementGuid>832acc03-ad89-4093-a8c2-a31c3c226910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News'])[1]/preceding::a[1]</value>
      <webElementGuid>c505cc25-1ef1-4d48-9677-7413ca27446a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Membership'])[1]/preceding::a[2]</value>
      <webElementGuid>b8716ac7-4768-4ae4-9694-a7d2dd031ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Resources']/parent::*</value>
      <webElementGuid>f769dc1c-8add-41fa-a76f-88eba87e37be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://neas.org.au/resources/')]</value>
      <webElementGuid>fbd4b02f-4646-4fa4-bde1-ce9070c80985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/nav/div/ul/li[3]/a</value>
      <webElementGuid>1b2a902f-6af3-43c2-9a0e-2dddd134e71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Resources' and @href = 'https://neas.org.au/resources/' and (text() = 'Resources' or . = 'Resources')]</value>
      <webElementGuid>38e73a61-6082-4b96-82f4-f5f629975fa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
