<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tham gia lp online min ph - Hc Ting An_03f404</name>
   <tag></tag>
   <elementGuidId>46017b75-f02b-4057-9854-ebb68c95a522</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e2']/div/div/div[3]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e2 > div.i_.div.si32 > div.i_.div.si33 > div.i_.div.si49 > a.p_.si27.a > span.span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Tham gia lớp online miễn phí - Học Tiếng Anh từ mất gốc&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>40933dbf-81ff-4b7f-9ab8-42d7639eaac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lines</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>f360198e-a8aa-4fb7-aa04-b50b4c1e3284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-truncate</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>38b6d4b6-c8d2-480e-ad71-f5b2d215b3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>05f00c18-692b-4137-9522-9387cd135052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tham gia lớp online miễn phí - Học Tiếng Anh từ mất gốc</value>
      <webElementGuid>65f492e4-4a81-4455-b134-f44bb7cf6e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e2&quot;)/div[@class=&quot;i_ div si32&quot;]/div[@class=&quot;i_ div si33&quot;]/div[@class=&quot;i_ div si49&quot;]/a[@class=&quot;p_ si27 a&quot;]/span[@class=&quot;span&quot;]</value>
      <webElementGuid>f66a628e-3eb6-42a5-8c3a-a15cccd60032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lp Hc Ting Anh Online - Favoes/iframe_Trang 1 ca khong 40.600.000 kt qu ch_46e361</value>
      <webElementGuid>174a7fb4-e9ce-47cf-933a-910159aadd40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e2']/div/div/div[3]/a/span</value>
      <webElementGuid>6e4935ef-2754-4958-84c0-dc0861f3288e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://www.acet.edu.vn/'])[1]/following::span[1]</value>
      <webElementGuid>9575620d-d555-4c1b-8ca3-83288969d02a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACET'])[1]/following::span[1]</value>
      <webElementGuid>c35c9acb-7723-4c27-999d-82e1d88a94c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tham gia']/parent::*</value>
      <webElementGuid>ef2b7cfb-119b-4e6a-ac44-dd8d6e4fcec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[3]/a/span</value>
      <webElementGuid>e7bcba75-0415-4851-a667-2f8d7e4c5496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tham gia lớp online miễn phí - Học Tiếng Anh từ mất gốc' or . = 'Tham gia lớp online miễn phí - Học Tiếng Anh từ mất gốc')]</value>
      <webElementGuid>8f0edb28-d4f4-44dd-bde7-abbfefe1fe3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
