<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Min Ph Test Trnh  Anh Ng - Hc Th Ting _d9f2ff</name>
   <tag></tag>
   <elementGuidId>eecdd61d-908f-4b49-a706-e97b2f6340ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e1']/div/div/div[3]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.p_.si27.a > span.span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Miễn Phí Test Trình Độ Anh Ngữ - Học Thử Tiếng Anh Miễn Phí&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>011709b7-2595-42da-8cde-e19174b5a4da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lines</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>cb5221b8-1e68-4f4d-9464-9ca0d696e725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-truncate</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4ae4c2ec-0363-44f6-85c6-4a67ca5f56b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>14920a2f-e17c-40fa-975d-4b22712aca3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Miễn Phí Test Trình Độ Anh Ngữ - Học Thử Tiếng Anh Miễn Phí</value>
      <webElementGuid>0a76ee74-119e-45c1-88c5-57fe44940e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e1&quot;)/div[@class=&quot;i_ div si32&quot;]/div[@class=&quot;i_ div si33&quot;]/div[@class=&quot;i_ div si49&quot;]/a[@class=&quot;p_ si27 a&quot;]/span[@class=&quot;span&quot;]</value>
      <webElementGuid>badbecf4-4347-47f5-9ff9-4c3bae78c71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Lp Hc Ting Anh Online - Favoes/iframe_Trang 1 ca khong 40.600.000 kt qu ch_46e361</value>
      <webElementGuid>dd99e3d8-7c27-4c04-a565-6820e09f907d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e1']/div/div/div[3]/a/span</value>
      <webElementGuid>9c70f6f0-0361-436e-9637-23ad90523c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='học'])[1]/following::span[1]</value>
      <webElementGuid>4227e7d2-fc23-4156-8208-950c88ac29c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tienganh'])[1]/following::span[2]</value>
      <webElementGuid>3f3d29ae-4176-4a78-9350-1d5b1beca3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Miễn Phí Test Trình Độ']/parent::*</value>
      <webElementGuid>6623e751-6fd2-4240-a1ce-639b224b65ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/span</value>
      <webElementGuid>87b72290-725d-4ee7-a997-520ebc007395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Miễn Phí Test Trình Độ Anh Ngữ - Học Thử Tiếng Anh Miễn Phí' or . = 'Miễn Phí Test Trình Độ Anh Ngữ - Học Thử Tiếng Anh Miễn Phí')]</value>
      <webElementGuid>d87b4d13-9b9c-4376-b438-62ebbb115616</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
