<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_D dng i chiu v phn tch li trong bi lm _9baa41</name>
   <tag></tag>
   <elementGuidId>ed5c0500-e7db-4205-8ee8-1097e93d3ff2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='wd-5e0425a118824']/li[4]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(4) > span.list-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Dễ dàng đối chiếu và phân tích lỗi trong bài làm của bạn với đáp án chính thức&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ccc59c6b-044c-4fc9-aced-c42ad7ed1bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-content</value>
      <webElementGuid>83bad723-c2b6-4a34-a9b3-97e4eb8832a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dễ dàng đối chiếu và phân tích lỗi trong bài làm của bạn với đáp án chính thức</value>
      <webElementGuid>1f410d1d-92c6-40b0-ac26-b5ab12ff3626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wd-5e0425a118824&quot;)/li[4]/span[@class=&quot;list-content&quot;]</value>
      <webElementGuid>4a2aaea3-2692-48ee-ab04-d1bf7c029281</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='wd-5e0425a118824']/li[4]/span[2]</value>
      <webElementGuid>d41ae544-a5bb-434b-b6a9-d58e3b4de659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đánh giá chính xác năng lực hiện tại của bản thân để đưa ra chiến thuật luyện thi hợp lý'])[1]/following::span[2]</value>
      <webElementGuid>926d8a2b-4ec0-4576-9049-ee5666c4f7c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bộ tài liệu luyện thi IELTS mẫu của IDP tương đồng với bài thi IELTS thực tế'])[1]/following::span[4]</value>
      <webElementGuid>067a7d2c-2531-492d-b49a-7182ed9d0b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TẢI NGAY'])[1]/preceding::span[1]</value>
      <webElementGuid>c67076b5-bf80-4342-9816-a006da0e3606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Th7'])[1]/preceding::span[3]</value>
      <webElementGuid>73502872-3dba-4c33-a417-58ebbb08ad21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dễ dàng đối chiếu và phân tích lỗi trong bài làm của bạn với đáp án chính thức']/parent::*</value>
      <webElementGuid>23971f84-d9bb-4800-9b3a-bddc9889c455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/span[2]</value>
      <webElementGuid>6bb2679b-af38-4edd-abdd-616947f3bfb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Dễ dàng đối chiếu và phân tích lỗi trong bài làm của bạn với đáp án chính thức' or . = 'Dễ dàng đối chiếu và phân tích lỗi trong bài làm của bạn với đáp án chính thức')]</value>
      <webElementGuid>0d4c4b78-5051-4cbf-921e-1a16bc8bd3cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
