<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Images</name>
   <tag></tag>
   <elementGuidId>88d8095f-d0d8-4242-b2df-0236baef2d15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hdtb-sc']/div/div/div/div/div[2]/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.nPDzT.T3FoJb > div.YmvwI</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Images&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0e5b712b-5f2b-4e0c-bcf8-4ff5a15968b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>bVqjv</value>
      <webElementGuid>69d235dd-021a-43c3-aeb9-3bbaf51f555a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>YmvwI</value>
      <webElementGuid>16248d3e-46ea-440f-8c72-8c4508513486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Images</value>
      <webElementGuid>c691209f-ffdc-4ad3-ab18-e6eb1fd236b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hdtb-sc&quot;)/div[@class=&quot;PHj8of&quot;]/div[@class=&quot;qogDvd&quot;]/div[@class=&quot;crJ18e&quot;]/div[1]/div[2]/a[@class=&quot;nPDzT T3FoJb&quot;]/div[@class=&quot;YmvwI&quot;]</value>
      <webElementGuid>77654f35-dfa0-4650-bf18-ab835e90ec2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hdtb-sc']/div/div/div/div/div[2]/a/div</value>
      <webElementGuid>d6967b88-f17e-44ee-90ef-fbef788cfd60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::div[2]</value>
      <webElementGuid>43e82cf8-b29c-42ea-8438-0bda2bf69764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters and topics'])[1]/following::div[8]</value>
      <webElementGuid>b9c0e63b-ed93-4ed3-ad78-e9003d233a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News'])[1]/preceding::div[1]</value>
      <webElementGuid>67878639-8932-47fb-a592-5b5851b3c70a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Videos'])[1]/preceding::div[3]</value>
      <webElementGuid>68d93215-9046-4312-b46b-65864050b7de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Images']/parent::*</value>
      <webElementGuid>687b573a-65a0-4a3a-822f-58bc6ec163ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>771d2e5b-3143-4fa6-b1a4-d58ac2132d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Images' or . = 'Images')]</value>
      <webElementGuid>4b74caba-2553-4107-a74b-8a5719c33476</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
