<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Wikipedia</name>
   <tag></tag>
   <elementGuidId>cd88cc3f-f1b4-4477-8283-23bb18bb1c5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hdtb-sc']/div/div[2]/div/div/a/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.FMKtTb.UqcIvb.bSsRe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Add Wikipedia&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6f055ad4-bd9d-4bbe-b59c-2a4b373e9ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FMKtTb UqcIvb bSsRe</value>
      <webElementGuid>2c940259-d505-49d0-a3a3-c5ed995098db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>pIvPIe</value>
      <webElementGuid>ad63bd06-b239-4f33-bfca-b6eb3884c849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wikipedia</value>
      <webElementGuid>c000db61-0f2d-4f1d-a1fb-a90c9c70bc48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hdtb-sc&quot;)/div[@class=&quot;PHj8of J1AhHd&quot;]/div[@class=&quot;zp6Lyf FpfXM&quot;]/div[@class=&quot;IUOThf&quot;]/div[1]/a[@class=&quot;nPDzT T3FoJb&quot;]/div[@class=&quot;GKS7s&quot;]/span[@class=&quot;FMKtTb UqcIvb bSsRe&quot;]</value>
      <webElementGuid>720d4caa-5fbb-40f8-a4f7-0054496de9c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hdtb-sc']/div/div[2]/div/div/a/div/span</value>
      <webElementGuid>d65b0fc6-037c-40dc-9d6f-45f64e5656b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tools'])[1]/following::span[1]</value>
      <webElementGuid>f080eb1c-3780-42ca-a283-065d4667d6aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finance'])[1]/following::span[1]</value>
      <webElementGuid>0887cfe9-8c1e-4737-a61e-545c740dd790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wife'])[1]/preceding::span[1]</value>
      <webElementGuid>448917a7-ccb9-4c59-97d7-b7cd6d874122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disability'])[1]/preceding::span[2]</value>
      <webElementGuid>ddb6ff07-9da8-4c15-8348-642d7f62d318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Wikipedia']/parent::*</value>
      <webElementGuid>58e4a725-08f6-437e-b487-5af626a119d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/span</value>
      <webElementGuid>3b938547-8535-4436-ba27-d26c06514a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Wikipedia' or . = 'Wikipedia')]</value>
      <webElementGuid>25060eaa-102b-47cb-aa39-3cdbc17083e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
